resources:
  - firehose-node.yaml
  - graph-node.yaml
  - ipfs-node.yaml
  - ipfs-persistent-volume.yaml
  - firehose-persistent-volume.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: test-addresses-persistencecore-graph
    files:
      - configs-graph/firehose-node.json
      - configs-graph/firehose.yml
      - configs-graph/config.toml
      - configs-graph/config-graph-node.toml
