---
apiVersion: v1
kind: Service
metadata:
  name: persistencecore-validator
  labels:
    app.kubernetes.io/name: persistencecore-validator
spec:
  clusterIP: None
  ports:
    - name: p2p
      port: 26656
      protocol: TCP
      targetPort: 26656
    - name: rpc
      port: 26657
      protocol: TCP
      targetPort: 26657
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: persistencecore-validator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: persistencecore-validator
spec:
  serviceName: persistencecore-validator
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: persistencecore
      app.kubernetes.io/name: persistencecore-validator
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: persistencecore
        app.kubernetes.io/type: persistencecore-validator
        app.kubernetes.io/name: persistencecore-validator
        app.kubernetes.io/version: '0.1'
    spec:
      initContainers:
        - name: wait-for-genesis
          image: persistenceone/persistencecore:latest
          imagePullPolicy: Always
          env:
            - name: GENESIS_HOST
              value: persistencecore-genesis.dev-core
            - name: GENESIS_PORT
              value: "8081"
          command:
            - bash
            - "-c"
            - |
              while [ $(curl -sw '%{http_code}' http://$GENESIS_HOST.svc.cluster.local:$GENESIS_PORT/node_id -o /dev/null) -ne 200 ]; do
                echo "Genesis validator does not seem to be ready. Waiting for it to start..."
                sleep 10;
              done
              echo "Ready to start"
              exit 0
        - name: init-validator
          image: persistenceone/persistencecore:latest
          imagePullPolicy: Always
          env:
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: chain.id
                  name: persistencecore
            - name: HOME_DIR
              value: /persistencecore
            - name: GENESIS_HOST
              value: persistencecore-genesis.dev-core
            - name: GENESIS_PORT
              value: "8081"
          command:
            - bash
            - "-c"
            - |
              VAL_INDEX=${HOSTNAME##*-}
              echo "Validator Index: $VAL_INDEX"

              # rm -rf $HOME_DIR

              VAL_NAME=$(jq -r ".validators[$VAL_INDEX].name" /configs/validators.json)
              echo "Validator Index: $VAL_INDEX, Key name: $VAL_NAME"

              echo "Printing genesis file before init"
              ls -lrht $HOME_DIR/config

              jq -r ".validators[$VAL_INDEX].mnemonic" /configs/validators.json | persistenceCore init $VAL_NAME --chain-id $CHAIN_ID --home $HOME_DIR --recover
              jq -r ".validators[$VAL_INDEX].mnemonic" /configs/validators.json | persistenceCore keys add $VAL_NAME --recover --keyring-backend="test" --home $HOME_DIR

              curl http://$GENESIS_HOST.svc.cluster.local:$GENESIS_PORT/genesis -o $HOME_DIR/config/genesis.json
              echo "Genesis file that we got....."
              cat $HOME_DIR/config/genesis.json

              echo "All exports"
              export

              echo "Fetching genesis file"

              GENESIS_NODE_P2P=$(curl -s http://$GENESIS_HOST.svc.cluster.local:$GENESIS_PORT/node_id)@$GENESIS_HOST.svc.cluster.local:26656
              echo "Node P2P: $GENESIS_NODE_P2P"
              sed -i "s/persistent_peers = \"\"/persistent_peers = \"$GENESIS_NODE_P2P\"/g" $HOME_DIR/config/config.toml
              sed -i 's#"tcp://127.0.0.1:26657"#"tcp://0.0.0.0:26657"#g' $HOME_DIR/config/config.toml
              sed -i 's/timeout_commit = "5s"/timeout_commit = "1s"/g' $HOME_DIR/config/config.toml
              sed -i 's/timeout_propose = "3s"/timeout_propose = "1s"/g' $HOME_DIR/config/config.toml
              sed -i 's/index_all_keys = false/index_all_keys = true/g' $HOME_DIR/config/config.toml

              echo "Printing the whole config.toml file"
              cat $HOME_DIR/config/config.toml

              curl -s http://$GENESIS_HOST.svc.cluster.local:$GENESIS_PORT/pub_key
          resources:
            limits:
              cpu: "0.2"
              memory: "200M"
            requests:
              cpu: "0.1"
              memory: "200M"
          volumeMounts:
            - mountPath: /persistencecore
              name: validator-pv-storage
            - mountPath: /configs
              name: addresses
        # - name: sync-validator-to-network
        #   image: persistenceone/persistencecore:latest
        #   imagePullPolicy: Always
        #   env:
        #     - name: CHAIN_ID
        #       valueFrom:
        #         configMapKeyRef:
        #           key: chain.id
        #           name: persistencecore
        #     - name: HOME_DIR
        #       value: /persistencecore
        #     - name: GENESIS_HOST
        #       value: persistencecore-genesis.dev-core
        #     - name: GENESIS_PORT
        #       value: "8081"
        #   command:
        #     - bash
        #     - "-c"
        #     - |
        #       persistenceCore start --home $HOME_DIR
        #   resources:
        #     limits:
        #       cpu: "0.2"
        #       memory: "200M"
        #     requests:
        #       cpu: "0.1"
        #       memory: "200M"
        #   volumeMounts:
        #     - mountPath: /persistencecore
        #       name: persistencecore
        #     - mountPath: /configs
        #       name: addresses
      containers:
        - name: validator
          image: persistenceone/persistencecore
          imagePullPolicy: Always
          env:
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: chain.id
                  name: persistencecore
            - name: HOME_DIR
              value: /persistencecore
            - name: GENESIS_HOST
              value: persistencecore-genesis.dev-core
            - name: GENESIS_RPC_PORT
              value: "26657"
          command:
            - bash
            - "-c"
            - |
              # Starting the chain
              persistenceCore start --home $HOME_DIR
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - "-c"
                  - |
                   bash /scripts/create-staking-tx.sh > "/create-staking-tx.log"
          resources:
            limits:
              cpu: "1"
              memory: "1G"
            requests:
              cpu: "0.5"
              memory: "500M"
          volumeMounts:
            # - mountPath: /persistencecore
            #   name: persistencecore
            - mountPath: /persistencecore
              name: validator-pv-storage
            - mountPath: /configs
              name: addresses
            - mountPath: /scripts
              name: scripts
        - name: exposer-app
          image: persistenceone/exposer:latest
          imagePullPolicy: Always
          env:
            - name: HOME_DIR
              value: /persistencecore
            - name: GENESIS_FILE
              value: /persistencecore/config/genesis.json
            - name: PORT
              value: "8081"
            - name: CLIENT_NAME
              value: "persistencecore"
          command: [ "exposer" ]
          resources:
            limits:
              cpu: "0.1"
              memory: "100M"
            requests:
              cpu: "0.1"
              memory: "100M"
          volumeMounts:
            - mountPath: /persistencecore
              name: validator-pv-storage
      volumes:
        # - name: persistencecore
        #   emptyDir: { }
        - name: addresses
          configMap:
            name: test-addresses-persistencecore
        - name: scripts
          configMap:
            name: scripts
  volumeClaimTemplates:
  - metadata:
      name: validator-pv-storage
    spec:
      storageClassName: do-block-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
