chains:
  - name: core-1
    type: persistencecore
    numValidators: 4
    upgrade:
      enabled: true
      type: build
      genesis: v5.0.1
      upgrades:
        - name: v6
          version: anmol/v6
    ports:
      rpc: 26657
      rest: 1317
      p2p: 26656

explorer:
  enabled: true
