apiVersion: v1
kind: Service
metadata:
  name: wasm-validator-all
spec:
  type: ClusterIP
  ports:
    - name: p2p
      port: 26656
      protocol: TCP
      targetPort: 26656
    - name: rpc
      port: 26657
      protocol: TCP
      targetPort: 26657
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: rest
      port: 1317
      protocol: TCP
      targetPort: 1317
  selector:
    app.kubernetes.io/type: wasm-validator
